// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldKey, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldVersion, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// BinPath applies equality check predicate on the "bin_path" field. It's identical to BinPathEQ.
func BinPath(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldBinPath, v))
}

// ProtocolVersion applies equality check predicate on the "protocol_version" field. It's identical to ProtocolVersionEQ.
func ProtocolVersion(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldProtocolVersion, v))
}

// MagicCookieKey applies equality check predicate on the "magic_cookie_key" field. It's identical to MagicCookieKeyEQ.
func MagicCookieKey(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMagicCookieKey, v))
}

// MagicCookieValue applies equality check predicate on the "magic_cookie_value" field. It's identical to MagicCookieValueEQ.
func MagicCookieValue(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMagicCookieValue, v))
}

// Config applies equality check predicate on the "config" field. It's identical to ConfigEQ.
func Config(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldConfig, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldEnabled, v))
}

// AutoStart applies equality check predicate on the "auto_start" field. It's identical to AutoStartEQ.
func AutoStart(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAutoStart, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastError, v))
}

// LastStartedAt applies equality check predicate on the "last_started_at" field. It's identical to LastStartedAtEQ.
func LastStartedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastStartedAt, v))
}

// LastStoppedAt applies equality check predicate on the "last_stopped_at" field. It's identical to LastStoppedAtEQ.
func LastStoppedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastStoppedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldKey, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldVersion, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDescription, v))
}

// BinPathEQ applies the EQ predicate on the "bin_path" field.
func BinPathEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldBinPath, v))
}

// BinPathNEQ applies the NEQ predicate on the "bin_path" field.
func BinPathNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldBinPath, v))
}

// BinPathIn applies the In predicate on the "bin_path" field.
func BinPathIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldBinPath, vs...))
}

// BinPathNotIn applies the NotIn predicate on the "bin_path" field.
func BinPathNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldBinPath, vs...))
}

// BinPathGT applies the GT predicate on the "bin_path" field.
func BinPathGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldBinPath, v))
}

// BinPathGTE applies the GTE predicate on the "bin_path" field.
func BinPathGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldBinPath, v))
}

// BinPathLT applies the LT predicate on the "bin_path" field.
func BinPathLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldBinPath, v))
}

// BinPathLTE applies the LTE predicate on the "bin_path" field.
func BinPathLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldBinPath, v))
}

// BinPathContains applies the Contains predicate on the "bin_path" field.
func BinPathContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldBinPath, v))
}

// BinPathHasPrefix applies the HasPrefix predicate on the "bin_path" field.
func BinPathHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldBinPath, v))
}

// BinPathHasSuffix applies the HasSuffix predicate on the "bin_path" field.
func BinPathHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldBinPath, v))
}

// BinPathEqualFold applies the EqualFold predicate on the "bin_path" field.
func BinPathEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldBinPath, v))
}

// BinPathContainsFold applies the ContainsFold predicate on the "bin_path" field.
func BinPathContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldBinPath, v))
}

// ProtocolVersionEQ applies the EQ predicate on the "protocol_version" field.
func ProtocolVersionEQ(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldProtocolVersion, v))
}

// ProtocolVersionNEQ applies the NEQ predicate on the "protocol_version" field.
func ProtocolVersionNEQ(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldProtocolVersion, v))
}

// ProtocolVersionIn applies the In predicate on the "protocol_version" field.
func ProtocolVersionIn(vs ...uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionNotIn applies the NotIn predicate on the "protocol_version" field.
func ProtocolVersionNotIn(vs ...uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionGT applies the GT predicate on the "protocol_version" field.
func ProtocolVersionGT(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldProtocolVersion, v))
}

// ProtocolVersionGTE applies the GTE predicate on the "protocol_version" field.
func ProtocolVersionGTE(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldProtocolVersion, v))
}

// ProtocolVersionLT applies the LT predicate on the "protocol_version" field.
func ProtocolVersionLT(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldProtocolVersion, v))
}

// ProtocolVersionLTE applies the LTE predicate on the "protocol_version" field.
func ProtocolVersionLTE(v uint) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldProtocolVersion, v))
}

// MagicCookieKeyEQ applies the EQ predicate on the "magic_cookie_key" field.
func MagicCookieKeyEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMagicCookieKey, v))
}

// MagicCookieKeyNEQ applies the NEQ predicate on the "magic_cookie_key" field.
func MagicCookieKeyNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldMagicCookieKey, v))
}

// MagicCookieKeyIn applies the In predicate on the "magic_cookie_key" field.
func MagicCookieKeyIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldMagicCookieKey, vs...))
}

// MagicCookieKeyNotIn applies the NotIn predicate on the "magic_cookie_key" field.
func MagicCookieKeyNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldMagicCookieKey, vs...))
}

// MagicCookieKeyGT applies the GT predicate on the "magic_cookie_key" field.
func MagicCookieKeyGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldMagicCookieKey, v))
}

// MagicCookieKeyGTE applies the GTE predicate on the "magic_cookie_key" field.
func MagicCookieKeyGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldMagicCookieKey, v))
}

// MagicCookieKeyLT applies the LT predicate on the "magic_cookie_key" field.
func MagicCookieKeyLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldMagicCookieKey, v))
}

// MagicCookieKeyLTE applies the LTE predicate on the "magic_cookie_key" field.
func MagicCookieKeyLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldMagicCookieKey, v))
}

// MagicCookieKeyContains applies the Contains predicate on the "magic_cookie_key" field.
func MagicCookieKeyContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldMagicCookieKey, v))
}

// MagicCookieKeyHasPrefix applies the HasPrefix predicate on the "magic_cookie_key" field.
func MagicCookieKeyHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldMagicCookieKey, v))
}

// MagicCookieKeyHasSuffix applies the HasSuffix predicate on the "magic_cookie_key" field.
func MagicCookieKeyHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldMagicCookieKey, v))
}

// MagicCookieKeyEqualFold applies the EqualFold predicate on the "magic_cookie_key" field.
func MagicCookieKeyEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldMagicCookieKey, v))
}

// MagicCookieKeyContainsFold applies the ContainsFold predicate on the "magic_cookie_key" field.
func MagicCookieKeyContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldMagicCookieKey, v))
}

// MagicCookieValueEQ applies the EQ predicate on the "magic_cookie_value" field.
func MagicCookieValueEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldMagicCookieValue, v))
}

// MagicCookieValueNEQ applies the NEQ predicate on the "magic_cookie_value" field.
func MagicCookieValueNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldMagicCookieValue, v))
}

// MagicCookieValueIn applies the In predicate on the "magic_cookie_value" field.
func MagicCookieValueIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldMagicCookieValue, vs...))
}

// MagicCookieValueNotIn applies the NotIn predicate on the "magic_cookie_value" field.
func MagicCookieValueNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldMagicCookieValue, vs...))
}

// MagicCookieValueGT applies the GT predicate on the "magic_cookie_value" field.
func MagicCookieValueGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldMagicCookieValue, v))
}

// MagicCookieValueGTE applies the GTE predicate on the "magic_cookie_value" field.
func MagicCookieValueGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldMagicCookieValue, v))
}

// MagicCookieValueLT applies the LT predicate on the "magic_cookie_value" field.
func MagicCookieValueLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldMagicCookieValue, v))
}

// MagicCookieValueLTE applies the LTE predicate on the "magic_cookie_value" field.
func MagicCookieValueLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldMagicCookieValue, v))
}

// MagicCookieValueContains applies the Contains predicate on the "magic_cookie_value" field.
func MagicCookieValueContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldMagicCookieValue, v))
}

// MagicCookieValueHasPrefix applies the HasPrefix predicate on the "magic_cookie_value" field.
func MagicCookieValueHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldMagicCookieValue, v))
}

// MagicCookieValueHasSuffix applies the HasSuffix predicate on the "magic_cookie_value" field.
func MagicCookieValueHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldMagicCookieValue, v))
}

// MagicCookieValueEqualFold applies the EqualFold predicate on the "magic_cookie_value" field.
func MagicCookieValueEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldMagicCookieValue, v))
}

// MagicCookieValueContainsFold applies the ContainsFold predicate on the "magic_cookie_value" field.
func MagicCookieValueContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldMagicCookieValue, v))
}

// DependenciesIsNil applies the IsNil predicate on the "dependencies" field.
func DependenciesIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldDependencies))
}

// DependenciesNotNil applies the NotNil predicate on the "dependencies" field.
func DependenciesNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldDependencies))
}

// ConfigEQ applies the EQ predicate on the "config" field.
func ConfigEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldConfig, v))
}

// ConfigNEQ applies the NEQ predicate on the "config" field.
func ConfigNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldConfig, v))
}

// ConfigIn applies the In predicate on the "config" field.
func ConfigIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldConfig, vs...))
}

// ConfigNotIn applies the NotIn predicate on the "config" field.
func ConfigNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldConfig, vs...))
}

// ConfigGT applies the GT predicate on the "config" field.
func ConfigGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldConfig, v))
}

// ConfigGTE applies the GTE predicate on the "config" field.
func ConfigGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldConfig, v))
}

// ConfigLT applies the LT predicate on the "config" field.
func ConfigLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldConfig, v))
}

// ConfigLTE applies the LTE predicate on the "config" field.
func ConfigLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldConfig, v))
}

// ConfigContains applies the Contains predicate on the "config" field.
func ConfigContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldConfig, v))
}

// ConfigHasPrefix applies the HasPrefix predicate on the "config" field.
func ConfigHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldConfig, v))
}

// ConfigHasSuffix applies the HasSuffix predicate on the "config" field.
func ConfigHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldConfig, v))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldConfig))
}

// ConfigEqualFold applies the EqualFold predicate on the "config" field.
func ConfigEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldConfig, v))
}

// ConfigContainsFold applies the ContainsFold predicate on the "config" field.
func ConfigContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldConfig, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldEnabled, v))
}

// AutoStartEQ applies the EQ predicate on the "auto_start" field.
func AutoStartEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAutoStart, v))
}

// AutoStartNEQ applies the NEQ predicate on the "auto_start" field.
func AutoStartNEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldAutoStart, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldStatus, vs...))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldLastError, v))
}

// LastStartedAtEQ applies the EQ predicate on the "last_started_at" field.
func LastStartedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastStartedAt, v))
}

// LastStartedAtNEQ applies the NEQ predicate on the "last_started_at" field.
func LastStartedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLastStartedAt, v))
}

// LastStartedAtIn applies the In predicate on the "last_started_at" field.
func LastStartedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLastStartedAt, vs...))
}

// LastStartedAtNotIn applies the NotIn predicate on the "last_started_at" field.
func LastStartedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLastStartedAt, vs...))
}

// LastStartedAtGT applies the GT predicate on the "last_started_at" field.
func LastStartedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLastStartedAt, v))
}

// LastStartedAtGTE applies the GTE predicate on the "last_started_at" field.
func LastStartedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLastStartedAt, v))
}

// LastStartedAtLT applies the LT predicate on the "last_started_at" field.
func LastStartedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLastStartedAt, v))
}

// LastStartedAtLTE applies the LTE predicate on the "last_started_at" field.
func LastStartedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLastStartedAt, v))
}

// LastStartedAtIsNil applies the IsNil predicate on the "last_started_at" field.
func LastStartedAtIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldLastStartedAt))
}

// LastStartedAtNotNil applies the NotNil predicate on the "last_started_at" field.
func LastStartedAtNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldLastStartedAt))
}

// LastStoppedAtEQ applies the EQ predicate on the "last_stopped_at" field.
func LastStoppedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastStoppedAt, v))
}

// LastStoppedAtNEQ applies the NEQ predicate on the "last_stopped_at" field.
func LastStoppedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLastStoppedAt, v))
}

// LastStoppedAtIn applies the In predicate on the "last_stopped_at" field.
func LastStoppedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLastStoppedAt, vs...))
}

// LastStoppedAtNotIn applies the NotIn predicate on the "last_stopped_at" field.
func LastStoppedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLastStoppedAt, vs...))
}

// LastStoppedAtGT applies the GT predicate on the "last_stopped_at" field.
func LastStoppedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLastStoppedAt, v))
}

// LastStoppedAtGTE applies the GTE predicate on the "last_stopped_at" field.
func LastStoppedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLastStoppedAt, v))
}

// LastStoppedAtLT applies the LT predicate on the "last_stopped_at" field.
func LastStoppedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLastStoppedAt, v))
}

// LastStoppedAtLTE applies the LTE predicate on the "last_stopped_at" field.
func LastStoppedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLastStoppedAt, v))
}

// LastStoppedAtIsNil applies the IsNil predicate on the "last_stopped_at" field.
func LastStoppedAtIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldLastStoppedAt))
}

// LastStoppedAtNotNil applies the NotNil predicate on the "last_stopped_at" field.
func LastStoppedAtNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldLastStoppedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.NotPredicates(p))
}
