// Code generated by ent, DO NOT EDIT.

package knowledgebase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldName, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldModel, v))
}

// VectorDimension applies equality check predicate on the "vector_dimension" field. It's identical to VectorDimensionEQ.
func VectorDimension(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldVectorDimension, v))
}

// MaxBatchDocumentCount applies equality check predicate on the "max_batch_document_count" field. It's identical to MaxBatchDocumentCountEQ.
func MaxBatchDocumentCount(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldMaxBatchDocumentCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldName, v))
}

// ModelProviderEQ applies the EQ predicate on the "model_provider" field.
func ModelProviderEQ(v ModelProvider) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldModelProvider, v))
}

// ModelProviderNEQ applies the NEQ predicate on the "model_provider" field.
func ModelProviderNEQ(v ModelProvider) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldModelProvider, v))
}

// ModelProviderIn applies the In predicate on the "model_provider" field.
func ModelProviderIn(vs ...ModelProvider) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldModelProvider, vs...))
}

// ModelProviderNotIn applies the NotIn predicate on the "model_provider" field.
func ModelProviderNotIn(vs ...ModelProvider) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldModelProvider, vs...))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldModel, v))
}

// VectorDimensionEQ applies the EQ predicate on the "vector_dimension" field.
func VectorDimensionEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldVectorDimension, v))
}

// VectorDimensionNEQ applies the NEQ predicate on the "vector_dimension" field.
func VectorDimensionNEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldVectorDimension, v))
}

// VectorDimensionIn applies the In predicate on the "vector_dimension" field.
func VectorDimensionIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldVectorDimension, vs...))
}

// VectorDimensionNotIn applies the NotIn predicate on the "vector_dimension" field.
func VectorDimensionNotIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldVectorDimension, vs...))
}

// VectorDimensionGT applies the GT predicate on the "vector_dimension" field.
func VectorDimensionGT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldVectorDimension, v))
}

// VectorDimensionGTE applies the GTE predicate on the "vector_dimension" field.
func VectorDimensionGTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldVectorDimension, v))
}

// VectorDimensionLT applies the LT predicate on the "vector_dimension" field.
func VectorDimensionLT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldVectorDimension, v))
}

// VectorDimensionLTE applies the LTE predicate on the "vector_dimension" field.
func VectorDimensionLTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldVectorDimension, v))
}

// MaxBatchDocumentCountEQ applies the EQ predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldMaxBatchDocumentCount, v))
}

// MaxBatchDocumentCountNEQ applies the NEQ predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountNEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldMaxBatchDocumentCount, v))
}

// MaxBatchDocumentCountIn applies the In predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldMaxBatchDocumentCount, vs...))
}

// MaxBatchDocumentCountNotIn applies the NotIn predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountNotIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldMaxBatchDocumentCount, vs...))
}

// MaxBatchDocumentCountGT applies the GT predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountGT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldMaxBatchDocumentCount, v))
}

// MaxBatchDocumentCountGTE applies the GTE predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountGTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldMaxBatchDocumentCount, v))
}

// MaxBatchDocumentCountLT applies the LT predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountLT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldMaxBatchDocumentCount, v))
}

// MaxBatchDocumentCountLTE applies the LTE predicate on the "max_batch_document_count" field.
func MaxBatchDocumentCountLTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldMaxBatchDocumentCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.NotPredicates(p))
}
