// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/plugin/proto/plugin_store.proto

// 包名：生成Go代码后的包名（可自定义，建议与公共包保持一致风格）

package plugin_store_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------
// 1. 空消息（用于无参数的请求/响应）
// 对应接口中无业务参数的方法（如 Info()、Version()、Health()）
// --------------------------
type EmptyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_store_proto_rawDescGZIP(), []int{0}
}

// --------------------------
// 2. 插件基础信息消息（核心数据载体）
// 对应公共包中的 PluginBasicInfo 结构体
// --------------------------
type PluginBasicInfoMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // 插件唯一标识（如 demo-plugin）
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 插件展示名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                    // 插件详细描述（可选）
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`                              // 插件作者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginBasicInfoMsg) Reset() {
	*x = PluginBasicInfoMsg{}
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginBasicInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginBasicInfoMsg) ProtoMessage() {}

func (x *PluginBasicInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginBasicInfoMsg.ProtoReflect.Descriptor instead.
func (*PluginBasicInfoMsg) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_store_proto_rawDescGZIP(), []int{1}
}

func (x *PluginBasicInfoMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginBasicInfoMsg) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginBasicInfoMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginBasicInfoMsg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// --------------------------
// 3. 版本消息（返回插件版本）
// 对应接口中的 Version() 方法返回值
// --------------------------
type VersionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // 语义化版本号（如 v1.0.0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionMsg) Reset() {
	*x = VersionMsg{}
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMsg) ProtoMessage() {}

func (x *VersionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMsg.ProtoReflect.Descriptor instead.
func (*VersionMsg) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_store_proto_rawDescGZIP(), []int{2}
}

func (x *VersionMsg) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// --------------------------
// 4. 初始化消息（宿主向插件注入配置）
// 对应接口中的 Init() 方法参数
// --------------------------
type InitMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置键值对（如 plugin_name、version）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMsg) Reset() {
	*x = InitMsg{}
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMsg) ProtoMessage() {}

func (x *InitMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMsg.ProtoReflect.Descriptor instead.
func (*InitMsg) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_store_proto_rawDescGZIP(), []int{3}
}

func (x *InitMsg) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// --------------------------
// 5. 健康检查消息（返回插件健康状态）
// 对应接口中的 Health() 方法返回值
// --------------------------
type HealthMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"` // 插件是否健康（true：健康，false：异常）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMsg) Reset() {
	*x = HealthMsg{}
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMsg) ProtoMessage() {}

func (x *HealthMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMsg.ProtoReflect.Descriptor instead.
func (*HealthMsg) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_store_proto_rawDescGZIP(), []int{4}
}

func (x *HealthMsg) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

var File_pkg_plugin_proto_plugin_store_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_store_proto_rawDesc = "" +
	"\n" +
	"#pkg/plugin/proto/plugin_store.proto\x12\fplugin_store\"\n" +
	"\n" +
	"\bEmptyMsg\"\x85\x01\n" +
	"\x12PluginBasicInfoMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\"&\n" +
	"\n" +
	"VersionMsg\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x7f\n" +
	"\aInitMsg\x129\n" +
	"\x06config\x18\x01 \x03(\v2!.plugin_store.InitMsg.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\tHealthMsg\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy2\xc0\x02\n" +
	"\x12PluginStoreService\x12@\n" +
	"\x04Info\x12\x16.plugin_store.EmptyMsg\x1a .plugin_store.PluginBasicInfoMsg\x12;\n" +
	"\aVersion\x12\x16.plugin_store.EmptyMsg\x1a\x18.plugin_store.VersionMsg\x125\n" +
	"\x04Init\x12\x15.plugin_store.InitMsg\x1a\x16.plugin_store.EmptyMsg\x129\n" +
	"\aDestroy\x12\x16.plugin_store.EmptyMsg\x1a\x16.plugin_store.EmptyMsg\x129\n" +
	"\x06Health\x12\x16.plugin_store.EmptyMsg\x1a\x17.plugin_store.HealthMsgB\x17Z\x15../pb;plugin_store_pbb\x06proto3"

var (
	file_pkg_plugin_proto_plugin_store_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_store_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_store_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_store_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_store_proto_rawDesc), len(file_pkg_plugin_proto_plugin_store_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_store_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_store_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_plugin_proto_plugin_store_proto_goTypes = []any{
	(*EmptyMsg)(nil),           // 0: plugin_store.EmptyMsg
	(*PluginBasicInfoMsg)(nil), // 1: plugin_store.PluginBasicInfoMsg
	(*VersionMsg)(nil),         // 2: plugin_store.VersionMsg
	(*InitMsg)(nil),            // 3: plugin_store.InitMsg
	(*HealthMsg)(nil),          // 4: plugin_store.HealthMsg
	nil,                        // 5: plugin_store.InitMsg.ConfigEntry
}
var file_pkg_plugin_proto_plugin_store_proto_depIdxs = []int32{
	5, // 0: plugin_store.InitMsg.config:type_name -> plugin_store.InitMsg.ConfigEntry
	0, // 1: plugin_store.PluginStoreService.Info:input_type -> plugin_store.EmptyMsg
	0, // 2: plugin_store.PluginStoreService.Version:input_type -> plugin_store.EmptyMsg
	3, // 3: plugin_store.PluginStoreService.Init:input_type -> plugin_store.InitMsg
	0, // 4: plugin_store.PluginStoreService.Destroy:input_type -> plugin_store.EmptyMsg
	0, // 5: plugin_store.PluginStoreService.Health:input_type -> plugin_store.EmptyMsg
	1, // 6: plugin_store.PluginStoreService.Info:output_type -> plugin_store.PluginBasicInfoMsg
	2, // 7: plugin_store.PluginStoreService.Version:output_type -> plugin_store.VersionMsg
	0, // 8: plugin_store.PluginStoreService.Init:output_type -> plugin_store.EmptyMsg
	0, // 9: plugin_store.PluginStoreService.Destroy:output_type -> plugin_store.EmptyMsg
	4, // 10: plugin_store.PluginStoreService.Health:output_type -> plugin_store.HealthMsg
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_store_proto_init() }
func file_pkg_plugin_proto_plugin_store_proto_init() {
	if File_pkg_plugin_proto_plugin_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_store_proto_rawDesc), len(file_pkg_plugin_proto_plugin_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_store_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_store_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_store_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_store_proto = out.File
	file_pkg_plugin_proto_plugin_store_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_store_proto_depIdxs = nil
}
