// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/doclibrary"
	"github.com/shuTwT/hoshikuzu/ent/doclibrarydetail"
)

// DocLibraryCreate is the builder for creating a DocLibrary entity.
type DocLibraryCreate struct {
	config
	mutation *DocLibraryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocLibraryCreate) SetCreatedAt(v time.Time) *DocLibraryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocLibraryCreate) SetNillableCreatedAt(v *time.Time) *DocLibraryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DocLibraryCreate) SetUpdatedAt(v time.Time) *DocLibraryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DocLibraryCreate) SetNillableUpdatedAt(v *time.Time) *DocLibraryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DocLibraryCreate) SetName(v string) *DocLibraryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAlias sets the "alias" field.
func (_c *DocLibraryCreate) SetAlias(v string) *DocLibraryCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DocLibraryCreate) SetDescription(v string) *DocLibraryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DocLibraryCreate) SetNillableDescription(v *string) *DocLibraryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *DocLibraryCreate) SetSource(v doclibrary.Source) *DocLibraryCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *DocLibraryCreate) SetURL(v string) *DocLibraryCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DocLibraryCreate) SetID(v int) *DocLibraryCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddDetailIDs adds the "details" edge to the DocLibraryDetail entity by IDs.
func (_c *DocLibraryCreate) AddDetailIDs(ids ...int) *DocLibraryCreate {
	_c.mutation.AddDetailIDs(ids...)
	return _c
}

// AddDetails adds the "details" edges to the DocLibraryDetail entity.
func (_c *DocLibraryCreate) AddDetails(v ...*DocLibraryDetail) *DocLibraryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDetailIDs(ids...)
}

// Mutation returns the DocLibraryMutation object of the builder.
func (_c *DocLibraryCreate) Mutation() *DocLibraryMutation {
	return _c.mutation
}

// Save creates the DocLibrary in the database.
func (_c *DocLibraryCreate) Save(ctx context.Context) (*DocLibrary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocLibraryCreate) SaveX(ctx context.Context) *DocLibrary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocLibraryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocLibraryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocLibraryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := doclibrary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := doclibrary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocLibraryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocLibrary.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DocLibrary.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DocLibrary.name"`)}
	}
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "DocLibrary.alias"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "DocLibrary.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := doclibrary.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "DocLibrary.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "DocLibrary.url"`)}
	}
	return nil
}

func (_c *DocLibraryCreate) sqlSave(ctx context.Context) (*DocLibrary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocLibraryCreate) createSpec() (*DocLibrary, *sqlgraph.CreateSpec) {
	var (
		_node = &DocLibrary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(doclibrary.Table, sqlgraph.NewFieldSpec(doclibrary.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(doclibrary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(doclibrary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(doclibrary.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(doclibrary.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(doclibrary.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(doclibrary.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(doclibrary.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if nodes := _c.mutation.DetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doclibrary.DetailsTable,
			Columns: []string{doclibrary.DetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doclibrarydetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocLibraryCreateBulk is the builder for creating many DocLibrary entities in bulk.
type DocLibraryCreateBulk struct {
	config
	err      error
	builders []*DocLibraryCreate
}

// Save creates the DocLibrary entities in the database.
func (_c *DocLibraryCreateBulk) Save(ctx context.Context) ([]*DocLibrary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocLibrary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocLibraryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocLibraryCreateBulk) SaveX(ctx context.Context) []*DocLibrary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocLibraryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocLibraryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
