// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/flink"
	"github.com/shuTwT/hoshikuzu/ent/flinkgroup"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// FLinkUpdate is the builder for updating FLink entities.
type FLinkUpdate struct {
	config
	hooks    []Hook
	mutation *FLinkMutation
}

// Where appends a list predicates to the FLinkUpdate builder.
func (_u *FLinkUpdate) Where(ps ...predicate.FLink) *FLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FLinkUpdate) SetUpdatedAt(v time.Time) *FLinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *FLinkUpdate) SetName(v string) *FLinkUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableName(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *FLinkUpdate) SetURL(v string) *FLinkUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableURL(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *FLinkUpdate) SetAvatarURL(v string) *FLinkUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableAvatarURL(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *FLinkUpdate) ClearAvatarURL() *FLinkUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetDescription sets the "description" field.
func (_u *FLinkUpdate) SetDescription(v string) *FLinkUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableDescription(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FLinkUpdate) ClearDescription() *FLinkUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FLinkUpdate) SetStatus(v int) *FLinkUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableStatus(v *int) *FLinkUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *FLinkUpdate) AddStatus(v int) *FLinkUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetSnapshotURL sets the "snapshot_url" field.
func (_u *FLinkUpdate) SetSnapshotURL(v string) *FLinkUpdate {
	_u.mutation.SetSnapshotURL(v)
	return _u
}

// SetNillableSnapshotURL sets the "snapshot_url" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableSnapshotURL(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetSnapshotURL(*v)
	}
	return _u
}

// ClearSnapshotURL clears the value of the "snapshot_url" field.
func (_u *FLinkUpdate) ClearSnapshotURL() *FLinkUpdate {
	_u.mutation.ClearSnapshotURL()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *FLinkUpdate) SetCoverURL(v string) *FLinkUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableCoverURL(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *FLinkUpdate) ClearCoverURL() *FLinkUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetEmail sets the "email" field.
func (_u *FLinkUpdate) SetEmail(v string) *FLinkUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableEmail(v *string) *FLinkUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *FLinkUpdate) ClearEmail() *FLinkUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *FLinkUpdate) SetGroupID(v int) *FLinkUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableGroupID(v *int) *FLinkUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *FLinkUpdate) ClearGroupID() *FLinkUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetEnableFriendCircle sets the "enable_friend_circle" field.
func (_u *FLinkUpdate) SetEnableFriendCircle(v bool) *FLinkUpdate {
	_u.mutation.SetEnableFriendCircle(v)
	return _u
}

// SetNillableEnableFriendCircle sets the "enable_friend_circle" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableEnableFriendCircle(v *bool) *FLinkUpdate {
	if v != nil {
		_u.SetEnableFriendCircle(*v)
	}
	return _u
}

// SetFriendCircleRuleID sets the "friend_circle_rule_id" field.
func (_u *FLinkUpdate) SetFriendCircleRuleID(v int) *FLinkUpdate {
	_u.mutation.ResetFriendCircleRuleID()
	_u.mutation.SetFriendCircleRuleID(v)
	return _u
}

// SetNillableFriendCircleRuleID sets the "friend_circle_rule_id" field if the given value is not nil.
func (_u *FLinkUpdate) SetNillableFriendCircleRuleID(v *int) *FLinkUpdate {
	if v != nil {
		_u.SetFriendCircleRuleID(*v)
	}
	return _u
}

// AddFriendCircleRuleID adds value to the "friend_circle_rule_id" field.
func (_u *FLinkUpdate) AddFriendCircleRuleID(v int) *FLinkUpdate {
	_u.mutation.AddFriendCircleRuleID(v)
	return _u
}

// ClearFriendCircleRuleID clears the value of the "friend_circle_rule_id" field.
func (_u *FLinkUpdate) ClearFriendCircleRuleID() *FLinkUpdate {
	_u.mutation.ClearFriendCircleRuleID()
	return _u
}

// SetGroup sets the "group" edge to the FLinkGroup entity.
func (_u *FLinkUpdate) SetGroup(v *FLinkGroup) *FLinkUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the FLinkMutation object of the builder.
func (_u *FLinkUpdate) Mutation() *FLinkMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the FLinkGroup entity.
func (_u *FLinkUpdate) ClearGroup() *FLinkUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FLinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FLinkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FLinkUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := flink.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FLink.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := flink.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "FLink.url": %w`, err)}
		}
	}
	return nil
}

func (_u *FLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flink.Table, flink.Columns, sqlgraph.NewFieldSpec(flink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flink.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(flink.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(flink.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(flink.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(flink.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(flink.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(flink.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flink.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(flink.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SnapshotURL(); ok {
		_spec.SetField(flink.FieldSnapshotURL, field.TypeString, value)
	}
	if _u.mutation.SnapshotURLCleared() {
		_spec.ClearField(flink.FieldSnapshotURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(flink.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(flink.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(flink.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(flink.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.EnableFriendCircle(); ok {
		_spec.SetField(flink.FieldEnableFriendCircle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FriendCircleRuleID(); ok {
		_spec.SetField(flink.FieldFriendCircleRuleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFriendCircleRuleID(); ok {
		_spec.AddField(flink.FieldFriendCircleRuleID, field.TypeInt, value)
	}
	if _u.mutation.FriendCircleRuleIDCleared() {
		_spec.ClearField(flink.FieldFriendCircleRuleID, field.TypeInt)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flink.GroupTable,
			Columns: []string{flink.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flinkgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flink.GroupTable,
			Columns: []string{flink.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flinkgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FLinkUpdateOne is the builder for updating a single FLink entity.
type FLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FLinkMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FLinkUpdateOne) SetUpdatedAt(v time.Time) *FLinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *FLinkUpdateOne) SetName(v string) *FLinkUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableName(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *FLinkUpdateOne) SetURL(v string) *FLinkUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableURL(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *FLinkUpdateOne) SetAvatarURL(v string) *FLinkUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableAvatarURL(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *FLinkUpdateOne) ClearAvatarURL() *FLinkUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetDescription sets the "description" field.
func (_u *FLinkUpdateOne) SetDescription(v string) *FLinkUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableDescription(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FLinkUpdateOne) ClearDescription() *FLinkUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FLinkUpdateOne) SetStatus(v int) *FLinkUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableStatus(v *int) *FLinkUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *FLinkUpdateOne) AddStatus(v int) *FLinkUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetSnapshotURL sets the "snapshot_url" field.
func (_u *FLinkUpdateOne) SetSnapshotURL(v string) *FLinkUpdateOne {
	_u.mutation.SetSnapshotURL(v)
	return _u
}

// SetNillableSnapshotURL sets the "snapshot_url" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableSnapshotURL(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetSnapshotURL(*v)
	}
	return _u
}

// ClearSnapshotURL clears the value of the "snapshot_url" field.
func (_u *FLinkUpdateOne) ClearSnapshotURL() *FLinkUpdateOne {
	_u.mutation.ClearSnapshotURL()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *FLinkUpdateOne) SetCoverURL(v string) *FLinkUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableCoverURL(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *FLinkUpdateOne) ClearCoverURL() *FLinkUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetEmail sets the "email" field.
func (_u *FLinkUpdateOne) SetEmail(v string) *FLinkUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableEmail(v *string) *FLinkUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *FLinkUpdateOne) ClearEmail() *FLinkUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *FLinkUpdateOne) SetGroupID(v int) *FLinkUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableGroupID(v *int) *FLinkUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *FLinkUpdateOne) ClearGroupID() *FLinkUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetEnableFriendCircle sets the "enable_friend_circle" field.
func (_u *FLinkUpdateOne) SetEnableFriendCircle(v bool) *FLinkUpdateOne {
	_u.mutation.SetEnableFriendCircle(v)
	return _u
}

// SetNillableEnableFriendCircle sets the "enable_friend_circle" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableEnableFriendCircle(v *bool) *FLinkUpdateOne {
	if v != nil {
		_u.SetEnableFriendCircle(*v)
	}
	return _u
}

// SetFriendCircleRuleID sets the "friend_circle_rule_id" field.
func (_u *FLinkUpdateOne) SetFriendCircleRuleID(v int) *FLinkUpdateOne {
	_u.mutation.ResetFriendCircleRuleID()
	_u.mutation.SetFriendCircleRuleID(v)
	return _u
}

// SetNillableFriendCircleRuleID sets the "friend_circle_rule_id" field if the given value is not nil.
func (_u *FLinkUpdateOne) SetNillableFriendCircleRuleID(v *int) *FLinkUpdateOne {
	if v != nil {
		_u.SetFriendCircleRuleID(*v)
	}
	return _u
}

// AddFriendCircleRuleID adds value to the "friend_circle_rule_id" field.
func (_u *FLinkUpdateOne) AddFriendCircleRuleID(v int) *FLinkUpdateOne {
	_u.mutation.AddFriendCircleRuleID(v)
	return _u
}

// ClearFriendCircleRuleID clears the value of the "friend_circle_rule_id" field.
func (_u *FLinkUpdateOne) ClearFriendCircleRuleID() *FLinkUpdateOne {
	_u.mutation.ClearFriendCircleRuleID()
	return _u
}

// SetGroup sets the "group" edge to the FLinkGroup entity.
func (_u *FLinkUpdateOne) SetGroup(v *FLinkGroup) *FLinkUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the FLinkMutation object of the builder.
func (_u *FLinkUpdateOne) Mutation() *FLinkMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the FLinkGroup entity.
func (_u *FLinkUpdateOne) ClearGroup() *FLinkUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the FLinkUpdate builder.
func (_u *FLinkUpdateOne) Where(ps ...predicate.FLink) *FLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FLinkUpdateOne) Select(field string, fields ...string) *FLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FLink entity.
func (_u *FLinkUpdateOne) Save(ctx context.Context) (*FLink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FLinkUpdateOne) SaveX(ctx context.Context) *FLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FLinkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := flink.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FLink.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := flink.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "FLink.url": %w`, err)}
		}
	}
	return nil
}

func (_u *FLinkUpdateOne) sqlSave(ctx context.Context) (_node *FLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flink.Table, flink.Columns, sqlgraph.NewFieldSpec(flink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flink.FieldID)
		for _, f := range fields {
			if !flink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flink.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(flink.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(flink.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(flink.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(flink.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(flink.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(flink.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flink.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(flink.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SnapshotURL(); ok {
		_spec.SetField(flink.FieldSnapshotURL, field.TypeString, value)
	}
	if _u.mutation.SnapshotURLCleared() {
		_spec.ClearField(flink.FieldSnapshotURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(flink.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(flink.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(flink.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(flink.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.EnableFriendCircle(); ok {
		_spec.SetField(flink.FieldEnableFriendCircle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FriendCircleRuleID(); ok {
		_spec.SetField(flink.FieldFriendCircleRuleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFriendCircleRuleID(); ok {
		_spec.AddField(flink.FieldFriendCircleRuleID, field.TypeInt, value)
	}
	if _u.mutation.FriendCircleRuleIDCleared() {
		_spec.ClearField(flink.FieldFriendCircleRuleID, field.TypeInt)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flink.GroupTable,
			Columns: []string{flink.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flinkgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flink.GroupTable,
			Columns: []string{flink.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flinkgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
