// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/flink"
	"github.com/shuTwT/hoshikuzu/ent/flinkgroup"
)

// FLink is the model entity for the FLink schema.
type FLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 名称
	Name string `json:"name,omitempty"`
	// 链接
	URL string `json:"url,omitempty"`
	// 头像
	AvatarURL string `json:"avatar_url,omitempty"`
	// 简介
	Description string `json:"description,omitempty"`
	// 状态
	Status int `json:"status,omitempty"`
	// 网站截图
	SnapshotURL string `json:"snapshot_url,omitempty"`
	// 网站封面
	CoverURL string `json:"cover_url,omitempty"`
	// 邮箱
	Email string `json:"email,omitempty"`
	// 友链组
	GroupID int `json:"group_id,omitempty"`
	// 是否开启朋友圈
	EnableFriendCircle bool `json:"enable_friend_circle,omitempty"`
	// 朋友圈解析规则
	FriendCircleRuleID *int `json:"friend_circle_rule_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FLinkQuery when eager-loading is set.
	Edges        FLinkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FLinkEdges holds the relations/edges for other nodes in the graph.
type FLinkEdges struct {
	// Group holds the value of the group edge.
	Group *FLinkGroup `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FLinkEdges) GroupOrErr() (*FLinkGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flinkgroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flink.FieldEnableFriendCircle:
			values[i] = new(sql.NullBool)
		case flink.FieldID, flink.FieldStatus, flink.FieldGroupID, flink.FieldFriendCircleRuleID:
			values[i] = new(sql.NullInt64)
		case flink.FieldName, flink.FieldURL, flink.FieldAvatarURL, flink.FieldDescription, flink.FieldSnapshotURL, flink.FieldCoverURL, flink.FieldEmail:
			values[i] = new(sql.NullString)
		case flink.FieldCreatedAt, flink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FLink fields.
func (_m *FLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case flink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case flink.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case flink.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case flink.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = value.String
			}
		case flink.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case flink.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case flink.FieldSnapshotURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_url", values[i])
			} else if value.Valid {
				_m.SnapshotURL = value.String
			}
		case flink.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = value.String
			}
		case flink.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case flink.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = int(value.Int64)
			}
		case flink.FieldEnableFriendCircle:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_friend_circle", values[i])
			} else if value.Valid {
				_m.EnableFriendCircle = value.Bool
			}
		case flink.FieldFriendCircleRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field friend_circle_rule_id", values[i])
			} else if value.Valid {
				_m.FriendCircleRuleID = new(int)
				*_m.FriendCircleRuleID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FLink.
// This includes values selected through modifiers, order, etc.
func (_m *FLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the FLink entity.
func (_m *FLink) QueryGroup() *FLinkGroupQuery {
	return NewFLinkClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this FLink.
// Note that you need to call FLink.Unwrap() before calling this method if this FLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FLink) Update() *FLinkUpdateOne {
	return NewFLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FLink) Unwrap() *FLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FLink) String() string {
	var builder strings.Builder
	builder.WriteString("FLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(_m.AvatarURL)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("snapshot_url=")
	builder.WriteString(_m.SnapshotURL)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(_m.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("enable_friend_circle=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnableFriendCircle))
	builder.WriteString(", ")
	if v := _m.FriendCircleRuleID; v != nil {
		builder.WriteString("friend_circle_rule_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// FLinks is a parsable slice of FLink.
type FLinks []*FLink
