// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/friendcirclerecord"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// FriendCircleRecordDelete is the builder for deleting a FriendCircleRecord entity.
type FriendCircleRecordDelete struct {
	config
	hooks    []Hook
	mutation *FriendCircleRecordMutation
}

// Where appends a list predicates to the FriendCircleRecordDelete builder.
func (_d *FriendCircleRecordDelete) Where(ps ...predicate.FriendCircleRecord) *FriendCircleRecordDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FriendCircleRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FriendCircleRecordDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FriendCircleRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(friendcirclerecord.Table, sqlgraph.NewFieldSpec(friendcirclerecord.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FriendCircleRecordDeleteOne is the builder for deleting a single FriendCircleRecord entity.
type FriendCircleRecordDeleteOne struct {
	_d *FriendCircleRecordDelete
}

// Where appends a list predicates to the FriendCircleRecordDelete builder.
func (_d *FriendCircleRecordDeleteOne) Where(ps ...predicate.FriendCircleRecord) *FriendCircleRecordDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FriendCircleRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{friendcirclerecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FriendCircleRecordDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
