// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/knowledgebase"
)

// KnowledgeBaseCreate is the builder for creating a KnowledgeBase entity.
type KnowledgeBaseCreate struct {
	config
	mutation *KnowledgeBaseMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *KnowledgeBaseCreate) SetCreatedAt(v time.Time) *KnowledgeBaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KnowledgeBaseCreate) SetNillableCreatedAt(v *time.Time) *KnowledgeBaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KnowledgeBaseCreate) SetUpdatedAt(v time.Time) *KnowledgeBaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KnowledgeBaseCreate) SetNillableUpdatedAt(v *time.Time) *KnowledgeBaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *KnowledgeBaseCreate) SetName(v string) *KnowledgeBaseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetModelProvider sets the "model_provider" field.
func (_c *KnowledgeBaseCreate) SetModelProvider(v knowledgebase.ModelProvider) *KnowledgeBaseCreate {
	_c.mutation.SetModelProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *KnowledgeBaseCreate) SetModel(v string) *KnowledgeBaseCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetVectorDimension sets the "vector_dimension" field.
func (_c *KnowledgeBaseCreate) SetVectorDimension(v int) *KnowledgeBaseCreate {
	_c.mutation.SetVectorDimension(v)
	return _c
}

// SetMaxBatchDocumentCount sets the "max_batch_document_count" field.
func (_c *KnowledgeBaseCreate) SetMaxBatchDocumentCount(v int) *KnowledgeBaseCreate {
	_c.mutation.SetMaxBatchDocumentCount(v)
	return _c
}

// SetID sets the "id" field.
func (_c *KnowledgeBaseCreate) SetID(v int) *KnowledgeBaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (_c *KnowledgeBaseCreate) Mutation() *KnowledgeBaseMutation {
	return _c.mutation
}

// Save creates the KnowledgeBase in the database.
func (_c *KnowledgeBaseCreate) Save(ctx context.Context) (*KnowledgeBase, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KnowledgeBaseCreate) SaveX(ctx context.Context) *KnowledgeBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeBaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeBaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KnowledgeBaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := knowledgebase.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := knowledgebase.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KnowledgeBaseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KnowledgeBase.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "KnowledgeBase.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "KnowledgeBase.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := knowledgebase.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelProvider(); !ok {
		return &ValidationError{Name: "model_provider", err: errors.New(`ent: missing required field "KnowledgeBase.model_provider"`)}
	}
	if v, ok := _c.mutation.ModelProvider(); ok {
		if err := knowledgebase.ModelProviderValidator(v); err != nil {
			return &ValidationError{Name: "model_provider", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.model_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "KnowledgeBase.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := knowledgebase.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VectorDimension(); !ok {
		return &ValidationError{Name: "vector_dimension", err: errors.New(`ent: missing required field "KnowledgeBase.vector_dimension"`)}
	}
	if v, ok := _c.mutation.VectorDimension(); ok {
		if err := knowledgebase.VectorDimensionValidator(v); err != nil {
			return &ValidationError{Name: "vector_dimension", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.vector_dimension": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxBatchDocumentCount(); !ok {
		return &ValidationError{Name: "max_batch_document_count", err: errors.New(`ent: missing required field "KnowledgeBase.max_batch_document_count"`)}
	}
	if v, ok := _c.mutation.MaxBatchDocumentCount(); ok {
		if err := knowledgebase.MaxBatchDocumentCountValidator(v); err != nil {
			return &ValidationError{Name: "max_batch_document_count", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.max_batch_document_count": %w`, err)}
		}
	}
	return nil
}

func (_c *KnowledgeBaseCreate) sqlSave(ctx context.Context) (*KnowledgeBase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KnowledgeBaseCreate) createSpec() (*KnowledgeBase, *sqlgraph.CreateSpec) {
	var (
		_node = &KnowledgeBase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(knowledgebase.Table, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgebase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ModelProvider(); ok {
		_spec.SetField(knowledgebase.FieldModelProvider, field.TypeEnum, value)
		_node.ModelProvider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(knowledgebase.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.VectorDimension(); ok {
		_spec.SetField(knowledgebase.FieldVectorDimension, field.TypeInt, value)
		_node.VectorDimension = value
	}
	if value, ok := _c.mutation.MaxBatchDocumentCount(); ok {
		_spec.SetField(knowledgebase.FieldMaxBatchDocumentCount, field.TypeInt, value)
		_node.MaxBatchDocumentCount = value
	}
	return _node, _spec
}

// KnowledgeBaseCreateBulk is the builder for creating many KnowledgeBase entities in bulk.
type KnowledgeBaseCreateBulk struct {
	config
	err      error
	builders []*KnowledgeBaseCreate
}

// Save creates the KnowledgeBase entities in the database.
func (_c *KnowledgeBaseCreateBulk) Save(ctx context.Context) ([]*KnowledgeBase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KnowledgeBase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeBaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KnowledgeBaseCreateBulk) SaveX(ctx context.Context) []*KnowledgeBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeBaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeBaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
