// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/knowledgebase"
)

// KnowledgeBase is the model entity for the KnowledgeBase schema.
type KnowledgeBase struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 知识库名称
	Name string `json:"name,omitempty"`
	// 模型供应商
	ModelProvider knowledgebase.ModelProvider `json:"model_provider,omitempty"`
	// 模型名称
	Model string `json:"model,omitempty"`
	// 向量维度
	VectorDimension int `json:"vector_dimension,omitempty"`
	// 最大批量处理文档数量
	MaxBatchDocumentCount int `json:"max_batch_document_count,omitempty"`
	selectValues          sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KnowledgeBase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case knowledgebase.FieldID, knowledgebase.FieldVectorDimension, knowledgebase.FieldMaxBatchDocumentCount:
			values[i] = new(sql.NullInt64)
		case knowledgebase.FieldName, knowledgebase.FieldModelProvider, knowledgebase.FieldModel:
			values[i] = new(sql.NullString)
		case knowledgebase.FieldCreatedAt, knowledgebase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KnowledgeBase fields.
func (_m *KnowledgeBase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case knowledgebase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case knowledgebase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case knowledgebase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case knowledgebase.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case knowledgebase.FieldModelProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_provider", values[i])
			} else if value.Valid {
				_m.ModelProvider = knowledgebase.ModelProvider(value.String)
			}
		case knowledgebase.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case knowledgebase.FieldVectorDimension:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vector_dimension", values[i])
			} else if value.Valid {
				_m.VectorDimension = int(value.Int64)
			}
		case knowledgebase.FieldMaxBatchDocumentCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_batch_document_count", values[i])
			} else if value.Valid {
				_m.MaxBatchDocumentCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KnowledgeBase.
// This includes values selected through modifiers, order, etc.
func (_m *KnowledgeBase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KnowledgeBase.
// Note that you need to call KnowledgeBase.Unwrap() before calling this method if this KnowledgeBase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KnowledgeBase) Update() *KnowledgeBaseUpdateOne {
	return NewKnowledgeBaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KnowledgeBase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KnowledgeBase) Unwrap() *KnowledgeBase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KnowledgeBase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KnowledgeBase) String() string {
	var builder strings.Builder
	builder.WriteString("KnowledgeBase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("model_provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelProvider))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("vector_dimension=")
	builder.WriteString(fmt.Sprintf("%v", _m.VectorDimension))
	builder.WriteString(", ")
	builder.WriteString("max_batch_document_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxBatchDocumentCount))
	builder.WriteByte(')')
	return builder.String()
}

// KnowledgeBases is a parsable slice of KnowledgeBase.
type KnowledgeBases []*KnowledgeBase
