// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/notification"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdate) SetUpdatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NotificationUpdate) SetContent(v string) *NotificationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableContent(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPublishTime sets the "publish_time" field.
func (_u *NotificationUpdate) SetPublishTime(v time.Time) *NotificationUpdate {
	_u.mutation.SetPublishTime(v)
	return _u
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillablePublishTime(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetPublishTime(*v)
	}
	return _u
}

// ClearPublishTime clears the value of the "publish_time" field.
func (_u *NotificationUpdate) ClearPublishTime() *NotificationUpdate {
	_u.mutation.ClearPublishTime()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdate) SetIsRead(v bool) *NotificationUpdate {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIsRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishTime(); ok {
		_spec.SetField(notification.FieldPublishTime, field.TypeTime, value)
	}
	if _u.mutation.PublishTimeCleared() {
		_spec.ClearField(notification.FieldPublishTime, field.TypeTime)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdateOne) SetUpdatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NotificationUpdateOne) SetContent(v string) *NotificationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableContent(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPublishTime sets the "publish_time" field.
func (_u *NotificationUpdateOne) SetPublishTime(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetPublishTime(v)
	return _u
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillablePublishTime(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetPublishTime(*v)
	}
	return _u
}

// ClearPublishTime clears the value of the "publish_time" field.
func (_u *NotificationUpdateOne) ClearPublishTime() *NotificationUpdateOne {
	_u.mutation.ClearPublishTime()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdateOne) SetIsRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIsRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishTime(); ok {
		_spec.SetField(notification.FieldPublishTime, field.TypeTime, value)
	}
	if _u.mutation.PublishTimeCleared() {
		_spec.ClearField(notification.FieldPublishTime, field.TypeTime)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
