// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/oauth2refreshtoken"
)

// Oauth2RefreshToken is the model entity for the Oauth2RefreshToken schema.
type Oauth2RefreshToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 用户ID
	UserID int `json:"user_id,omitempty"`
	// 刷新令牌
	RefreshToken string `json:"refresh_token,omitempty"`
	// 客户端ID
	ClientID string `json:"client_id,omitempty"`
	// 授权范围
	Scope string `json:"scope,omitempty"`
	// 过期时间
	ExpireAt     time.Time `json:"expire_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Oauth2RefreshToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauth2refreshtoken.FieldID, oauth2refreshtoken.FieldUserID:
			values[i] = new(sql.NullInt64)
		case oauth2refreshtoken.FieldRefreshToken, oauth2refreshtoken.FieldClientID, oauth2refreshtoken.FieldScope:
			values[i] = new(sql.NullString)
		case oauth2refreshtoken.FieldCreatedAt, oauth2refreshtoken.FieldUpdatedAt, oauth2refreshtoken.FieldExpireAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Oauth2RefreshToken fields.
func (_m *Oauth2RefreshToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauth2refreshtoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oauth2refreshtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauth2refreshtoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauth2refreshtoken.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case oauth2refreshtoken.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = value.String
			}
		case oauth2refreshtoken.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauth2refreshtoken.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case oauth2refreshtoken.FieldExpireAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expire_at", values[i])
			} else if value.Valid {
				_m.ExpireAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Oauth2RefreshToken.
// This includes values selected through modifiers, order, etc.
func (_m *Oauth2RefreshToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Oauth2RefreshToken.
// Note that you need to call Oauth2RefreshToken.Unwrap() before calling this method if this Oauth2RefreshToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Oauth2RefreshToken) Update() *Oauth2RefreshTokenUpdateOne {
	return NewOauth2RefreshTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Oauth2RefreshToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Oauth2RefreshToken) Unwrap() *Oauth2RefreshToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Oauth2RefreshToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Oauth2RefreshToken) String() string {
	var builder strings.Builder
	builder.WriteString("Oauth2RefreshToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("refresh_token=")
	builder.WriteString(_m.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("expire_at=")
	builder.WriteString(_m.ExpireAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Oauth2RefreshTokens is a parsable slice of Oauth2RefreshToken.
type Oauth2RefreshTokens []*Oauth2RefreshToken
