// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/file"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
	"github.com/shuTwT/hoshikuzu/ent/storagestrategy"
)

// StorageStrategyUpdate is the builder for updating StorageStrategy entities.
type StorageStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *StorageStrategyMutation
}

// Where appends a list predicates to the StorageStrategyUpdate builder.
func (_u *StorageStrategyUpdate) Where(ps ...predicate.StorageStrategy) *StorageStrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StorageStrategyUpdate) SetUpdatedAt(v time.Time) *StorageStrategyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *StorageStrategyUpdate) SetName(v string) *StorageStrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableName(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *StorageStrategyUpdate) SetType(v storagestrategy.Type) *StorageStrategyUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableType(v *storagestrategy.Type) *StorageStrategyUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *StorageStrategyUpdate) SetNodeID(v string) *StorageStrategyUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableNodeID(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *StorageStrategyUpdate) SetEndpoint(v string) *StorageStrategyUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableEndpoint(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *StorageStrategyUpdate) SetRegion(v string) *StorageStrategyUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableRegion(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *StorageStrategyUpdate) SetBucket(v string) *StorageStrategyUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableBucket(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAccessKey sets the "access_key" field.
func (_u *StorageStrategyUpdate) SetAccessKey(v string) *StorageStrategyUpdate {
	_u.mutation.SetAccessKey(v)
	return _u
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableAccessKey(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetAccessKey(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *StorageStrategyUpdate) SetSecretKey(v string) *StorageStrategyUpdate {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableSecretKey(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetBasePath sets the "base_path" field.
func (_u *StorageStrategyUpdate) SetBasePath(v string) *StorageStrategyUpdate {
	_u.mutation.SetBasePath(v)
	return _u
}

// SetNillableBasePath sets the "base_path" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableBasePath(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetBasePath(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *StorageStrategyUpdate) SetDomain(v string) *StorageStrategyUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableDomain(v *string) *StorageStrategyUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetMaster sets the "master" field.
func (_u *StorageStrategyUpdate) SetMaster(v bool) *StorageStrategyUpdate {
	_u.mutation.SetMaster(v)
	return _u
}

// SetNillableMaster sets the "master" field if the given value is not nil.
func (_u *StorageStrategyUpdate) SetNillableMaster(v *bool) *StorageStrategyUpdate {
	if v != nil {
		_u.SetMaster(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *StorageStrategyUpdate) AddFileIDs(ids ...int) *StorageStrategyUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *StorageStrategyUpdate) AddFiles(v ...*File) *StorageStrategyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the StorageStrategyMutation object of the builder.
func (_u *StorageStrategyUpdate) Mutation() *StorageStrategyMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *StorageStrategyUpdate) ClearFiles() *StorageStrategyUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *StorageStrategyUpdate) RemoveFileIDs(ids ...int) *StorageStrategyUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *StorageStrategyUpdate) RemoveFiles(v ...*File) *StorageStrategyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StorageStrategyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StorageStrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageStrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StorageStrategyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storagestrategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageStrategyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := storagestrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StorageStrategy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := storagestrategy.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "StorageStrategy.type": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageStrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagestrategy.Table, storagestrategy.Columns, sqlgraph.NewFieldSpec(storagestrategy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storagestrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(storagestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(storagestrategy.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(storagestrategy.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(storagestrategy.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(storagestrategy.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(storagestrategy.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKey(); ok {
		_spec.SetField(storagestrategy.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(storagestrategy.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BasePath(); ok {
		_spec.SetField(storagestrategy.FieldBasePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(storagestrategy.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Master(); ok {
		_spec.SetField(storagestrategy.FieldMaster, field.TypeBool, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storagestrategy.FilesTable,
			Columns: []string{storagestrategy.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storagestrategy.FilesTable,
			Columns: []string{storagestrategy.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storagestrategy.FilesTable,
			Columns: []string{storagestrategy.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StorageStrategyUpdateOne is the builder for updating a single StorageStrategy entity.
type StorageStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageStrategyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StorageStrategyUpdateOne) SetUpdatedAt(v time.Time) *StorageStrategyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *StorageStrategyUpdateOne) SetName(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableName(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *StorageStrategyUpdateOne) SetType(v storagestrategy.Type) *StorageStrategyUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableType(v *storagestrategy.Type) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *StorageStrategyUpdateOne) SetNodeID(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableNodeID(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *StorageStrategyUpdateOne) SetEndpoint(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableEndpoint(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *StorageStrategyUpdateOne) SetRegion(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableRegion(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *StorageStrategyUpdateOne) SetBucket(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableBucket(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAccessKey sets the "access_key" field.
func (_u *StorageStrategyUpdateOne) SetAccessKey(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetAccessKey(v)
	return _u
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableAccessKey(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetAccessKey(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *StorageStrategyUpdateOne) SetSecretKey(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableSecretKey(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetBasePath sets the "base_path" field.
func (_u *StorageStrategyUpdateOne) SetBasePath(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetBasePath(v)
	return _u
}

// SetNillableBasePath sets the "base_path" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableBasePath(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetBasePath(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *StorageStrategyUpdateOne) SetDomain(v string) *StorageStrategyUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableDomain(v *string) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetMaster sets the "master" field.
func (_u *StorageStrategyUpdateOne) SetMaster(v bool) *StorageStrategyUpdateOne {
	_u.mutation.SetMaster(v)
	return _u
}

// SetNillableMaster sets the "master" field if the given value is not nil.
func (_u *StorageStrategyUpdateOne) SetNillableMaster(v *bool) *StorageStrategyUpdateOne {
	if v != nil {
		_u.SetMaster(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *StorageStrategyUpdateOne) AddFileIDs(ids ...int) *StorageStrategyUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *StorageStrategyUpdateOne) AddFiles(v ...*File) *StorageStrategyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the StorageStrategyMutation object of the builder.
func (_u *StorageStrategyUpdateOne) Mutation() *StorageStrategyMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *StorageStrategyUpdateOne) ClearFiles() *StorageStrategyUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *StorageStrategyUpdateOne) RemoveFileIDs(ids ...int) *StorageStrategyUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *StorageStrategyUpdateOne) RemoveFiles(v ...*File) *StorageStrategyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the StorageStrategyUpdate builder.
func (_u *StorageStrategyUpdateOne) Where(ps ...predicate.StorageStrategy) *StorageStrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StorageStrategyUpdateOne) Select(field string, fields ...string) *StorageStrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StorageStrategy entity.
func (_u *StorageStrategyUpdateOne) Save(ctx context.Context) (*StorageStrategy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageStrategyUpdateOne) SaveX(ctx context.Context) *StorageStrategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StorageStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StorageStrategyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storagestrategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageStrategyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := storagestrategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StorageStrategy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := storagestrategy.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "StorageStrategy.type": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageStrategyUpdateOne) sqlSave(ctx context.Context) (_node *StorageStrategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagestrategy.Table, storagestrategy.Columns, sqlgraph.NewFieldSpec(storagestrategy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StorageStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagestrategy.FieldID)
		for _, f := range fields {
			if !storagestrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storagestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storagestrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(storagestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(storagestrategy.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(storagestrategy.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(storagestrategy.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(storagestrategy.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(storagestrategy.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKey(); ok {
		_spec.SetField(storagestrategy.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(storagestrategy.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BasePath(); ok {
		_spec.SetField(storagestrategy.FieldBasePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(storagestrategy.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Master(); ok {
		_spec.SetField(storagestrategy.FieldMaster, field.TypeBool, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storagestrategy.FilesTable,
			Columns: []string{storagestrategy.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storagestrategy.FilesTable,
			Columns: []string{storagestrategy.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   storagestrategy.FilesTable,
			Columns: []string{storagestrategy.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StorageStrategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
