// Code generated by ent, DO NOT EDIT.

package couponusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// CouponCode applies equality check predicate on the "coupon_code" field. It's identical to CouponCodeEQ.
func CouponCode(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldCouponCode, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldOrderID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldStatus, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldUsedAt, v))
}

// DiscountAmount applies equality check predicate on the "discount_amount" field. It's identical to DiscountAmountEQ.
func DiscountAmount(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldDiscountAmount, v))
}

// ExpireAt applies equality check predicate on the "expire_at" field. It's identical to ExpireAtEQ.
func ExpireAt(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldExpireAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldUpdatedAt, v))
}

// CouponCodeEQ applies the EQ predicate on the "coupon_code" field.
func CouponCodeEQ(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldCouponCode, v))
}

// CouponCodeNEQ applies the NEQ predicate on the "coupon_code" field.
func CouponCodeNEQ(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldCouponCode, v))
}

// CouponCodeIn applies the In predicate on the "coupon_code" field.
func CouponCodeIn(vs ...string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldCouponCode, vs...))
}

// CouponCodeNotIn applies the NotIn predicate on the "coupon_code" field.
func CouponCodeNotIn(vs ...string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldCouponCode, vs...))
}

// CouponCodeGT applies the GT predicate on the "coupon_code" field.
func CouponCodeGT(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldCouponCode, v))
}

// CouponCodeGTE applies the GTE predicate on the "coupon_code" field.
func CouponCodeGTE(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldCouponCode, v))
}

// CouponCodeLT applies the LT predicate on the "coupon_code" field.
func CouponCodeLT(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldCouponCode, v))
}

// CouponCodeLTE applies the LTE predicate on the "coupon_code" field.
func CouponCodeLTE(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldCouponCode, v))
}

// CouponCodeContains applies the Contains predicate on the "coupon_code" field.
func CouponCodeContains(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldContains(FieldCouponCode, v))
}

// CouponCodeHasPrefix applies the HasPrefix predicate on the "coupon_code" field.
func CouponCodeHasPrefix(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldHasPrefix(FieldCouponCode, v))
}

// CouponCodeHasSuffix applies the HasSuffix predicate on the "coupon_code" field.
func CouponCodeHasSuffix(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldHasSuffix(FieldCouponCode, v))
}

// CouponCodeEqualFold applies the EqualFold predicate on the "coupon_code" field.
func CouponCodeEqualFold(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEqualFold(FieldCouponCode, v))
}

// CouponCodeContainsFold applies the ContainsFold predicate on the "coupon_code" field.
func CouponCodeContainsFold(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldContainsFold(FieldCouponCode, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldUserID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotNull(FieldOrderID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldStatus, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotNull(FieldUsedAt))
}

// DiscountAmountEQ applies the EQ predicate on the "discount_amount" field.
func DiscountAmountEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldDiscountAmount, v))
}

// DiscountAmountNEQ applies the NEQ predicate on the "discount_amount" field.
func DiscountAmountNEQ(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldDiscountAmount, v))
}

// DiscountAmountIn applies the In predicate on the "discount_amount" field.
func DiscountAmountIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldDiscountAmount, vs...))
}

// DiscountAmountNotIn applies the NotIn predicate on the "discount_amount" field.
func DiscountAmountNotIn(vs ...int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldDiscountAmount, vs...))
}

// DiscountAmountGT applies the GT predicate on the "discount_amount" field.
func DiscountAmountGT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldDiscountAmount, v))
}

// DiscountAmountGTE applies the GTE predicate on the "discount_amount" field.
func DiscountAmountGTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldDiscountAmount, v))
}

// DiscountAmountLT applies the LT predicate on the "discount_amount" field.
func DiscountAmountLT(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldDiscountAmount, v))
}

// DiscountAmountLTE applies the LTE predicate on the "discount_amount" field.
func DiscountAmountLTE(v int) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldDiscountAmount, v))
}

// ExpireAtEQ applies the EQ predicate on the "expire_at" field.
func ExpireAtEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldExpireAt, v))
}

// ExpireAtNEQ applies the NEQ predicate on the "expire_at" field.
func ExpireAtNEQ(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldExpireAt, v))
}

// ExpireAtIn applies the In predicate on the "expire_at" field.
func ExpireAtIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldExpireAt, vs...))
}

// ExpireAtNotIn applies the NotIn predicate on the "expire_at" field.
func ExpireAtNotIn(vs ...time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldExpireAt, vs...))
}

// ExpireAtGT applies the GT predicate on the "expire_at" field.
func ExpireAtGT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldExpireAt, v))
}

// ExpireAtGTE applies the GTE predicate on the "expire_at" field.
func ExpireAtGTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldExpireAt, v))
}

// ExpireAtLT applies the LT predicate on the "expire_at" field.
func ExpireAtLT(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldExpireAt, v))
}

// ExpireAtLTE applies the LTE predicate on the "expire_at" field.
func ExpireAtLTE(v time.Time) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldExpireAt, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.CouponUsage {
	return predicate.CouponUsage(sql.FieldContainsFold(FieldRemark, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CouponUsage) predicate.CouponUsage {
	return predicate.CouponUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CouponUsage) predicate.CouponUsage {
	return predicate.CouponUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CouponUsage) predicate.CouponUsage {
	return predicate.CouponUsage(sql.NotPredicates(p))
}
